name: flutter_example
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: any
  sqflite: ^2.0.3+1
  animate_do: ^2.1.0
  flutter_slidable: ^2.0.0
  quickalert: ^1.0.0
  lottie: ^2.4.0
  flutter_zoom_drawer: ^3.1.1
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0
  get: ^4.6.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  page_flip: ^0.2.3
  awesome_snackbar_content: ^0.1.3
  animated_theme_switcher: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
